name: drag_down_to_pop
description: A page transition which supports drag-down-to-pop gesture.
version: 1.0.0
homepage: https://github.com/nekocode/drag-down-to-pop-flutter

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=2.0.0 <2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
